class GameSourceError(Exception): ...


class PlayerNotFoundError(GameSourceError): ...


class InvalidGameError(ValueError): ...


class GameNotFoundError(LookupError): ...


class GameNotAnalyzedError(LookupError): ...
