class GameSourceError(Exception): ...


class PlayerNotFoundError(GameSourceError): ...


class InvalidGameError(ValueError): ...


class GameNotFoundError(LookupError): ...


class GameNotAnalyzedError(LookupError): ...


class PuzzleNotFoundError(LookupError): ...


class PuzzleNotAttemptedError(PermissionError): ...


class InvalidMoveError(ValueError): ...
